spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://34.118.204.224:8888}"

firestore:
  project-id: ${FIRESTORE_PROJECT_ID:buddhi-cloud}
  products-collection: ${FIRESTORE_PRODUCTS_COLLECTION:products}

server:
  address: 0.0.0.0
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
